# Generated by Django 2.2.1 on 2019-05-25 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='+380', max_length=14)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=25)),
                ('schedule', models.CharField(default='', max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_seats', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_datetime', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
                ('table', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Table')),
            ],
            options={
                'ordering': ['-order_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='img/photo/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('menu_item_id', models.ForeignKey(on_delete=None, to='core.MenuItem')),
            ],
            options={
                'ordering': ['alt_text'],
            },
        ),
    ]
