# Generated by Django 2.2.1 on 2019-05-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190525_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_datetime', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(default='', max_length=50)),
                ('text_review', models.TextField(default='')),
            ],
            options={
                'ordering': ['review_datetime'],
            },
        ),
    ]
